// Baza dječjih riječi za Dječnik (dječnik.hr)
// Sadrži izvorne riječi s plakata i autentične dječje neologizme

export const INITIAL_WORDS = [
  {
    id: "klopavac",
    letter: "K",
    word: "klopavac",
    realWord: "poklopac",
    definition: "pokretni predmet koji poklapa nešto da se ne vidi ili ne izlije.",
    speaker: "A.G.",
    age: 6,
    date: "04/06/2024",
    location: "Zagreb",
    year: 2024,
    tags: ["kuhinja", "predmeti"]
  },
  {
    id: "turutka",
    letter: "T",
    word: "turutka",
    realWord: "kruška",
    definition: "slatko voće s tankim vrhom i debelim dnom koje se jede kad je mekano.",
    speaker: "M.G.",
    age: 5,
    date: "12/09/2023",
    location: "Zagreb",
    year: 2023,
    tags: ["hrana", "voće"]
  },
  {
    id: "kliker",
    letter: "K",
    word: "kliker",
    realWord: "prekidač za svjetlo",
    definition: "dugme na zidu koje napravi 'klik' i onda u sobi postane dan.",
    speaker: "L.B.",
    age: 4,
    date: "15/01/2024",
    location: "Split",
    year: 2024,
    tags: ["kuća", "elektrika"]
  },
  {
    id: "koclijanac",
    letter: "K",
    word: "kočlijanac",
    realWord: "kočijaš / konj s kočijom",
    definition: "gospodin koji sjedi na drvenim kolima i govori konju 'đih'.",
    speaker: "F.V.",
    age: 5,
    date: "22/03/2024",
    location: "Osijek",
    year: 2024,
    tags: ["životinje", "priče"]
  },
  {
    id: "kokic",
    letter: "K",
    word: "kokic",
    realWord: "pijetao",
    definition: "tata od kokoši koji se rano ujutro dere na cijelo dvorište.",
    speaker: "P.K.",
    age: 3,
    date: "11/05/2024",
    location: "Varaždin",
    year: 2024,
    tags: ["životinje", "selo"]
  },
  {
    id: "krmac",
    letter: "K",
    word: "krmac",
    realWord: "daljinski upravljač",
    definition: "crna spravica s puno gumbića koja se stalno gubi među jastucima kauča.",
    speaker: "I.M.",
    age: 6,
    date: "02/02/2024",
    location: "Rijeka",
    year: 2024,
    tags: ["kuća", "tehnologija"]
  },
  {
    id: "krempita",
    letter: "K",
    word: "krempita",
    realWord: "krema za sunčanje",
    definition: "bijeli namaz koji mama maže po leđima prije ulaska u more da ne pocrveniš.",
    speaker: "E.J.",
    age: 4,
    date: "18/07/2023",
    location: "Zadar",
    year: 2023,
    tags: ["ljeto", "more"]
  },
  {
    id: "bavrljica",
    letter: "B",
    word: "bavrljica",
    realWord: "bumbarka / pčela",
    definition: "debela buba u žuto-crnom džemperu koja pije sok iz cvijeća.",
    speaker: "N.P.",
    age: 4,
    date: "05/05/2024",
    location: "Samobor",
    year: 2024,
    tags: ["priroda", "insekti"]
  },
  {
    id: "glistoljub",
    letter: "G",
    word: "glistoljub",
    realWord: "kišobran",
    definition: "velika gljiva na štapu koju nosimo kad pada kiša i izlaze gliste.",
    speaker: "T.R.",
    age: 5,
    date: "14/11/2023",
    location: "Karlovac",
    year: 2023,
    tags: ["vrijeme", "predmeti"]
  },
  {
    id: "svjetlica",
    letter: "S",
    word: "svjetlica",
    realWord: "baterijska lampa",
    definition: "čarobni štap koji svijetli u mraku ispod popluna.",
    speaker: "K.D.",
    age: 3,
    date: "08/12/2023",
    location: "Dubrovnik",
    year: 2023,
    tags: ["noć", "igračke"]
  },
  {
    id: "vlakopis",
    letter: "V",
    word: "vlakopis",
    realWord: "tračnice / pruga",
    definition: "željezne crte nacrtane po zemlji po kojima vlak mora voziti bez skretanja.",
    speaker: "J.Š.",
    age: 5,
    date: "29/04/2024",
    location: "Koprivnica",
    year: 2024,
    tags: ["promet", "putovanja"]
  },
  {
    id: "mackodlak",
    letter: "M",
    word: "mačkodlak",
    realWord: "debeli mačak",
    definition: "mačka koja jede previše briketa pa izgleda kao jastuk s brkovima.",
    speaker: "V.S.",
    age: 6,
    date: "10/01/2024",
    location: "Zagreb",
    year: 2024,
    tags: ["životinje", "humor"]
  },
  {
    id: "zvukotres",
    letter: "Z",
    word: "zvukotres",
    realWord: "grmljavina",
    definition: "kad se oblaci na nebu jako posvađaju i lupaju vratima.",
    speaker: "D.K.",
    age: 4,
    date: "03/06/2024",
    location: "Pula",
    year: 2024,
    tags: ["priroda", "vrijeme"]
  },
  {
    id: "nogacica",
    letter: "N",
    word: "nogačica",
    realWord: "stonoga",
    definition: "mali vlak s puno cipela koji živi ispod kamena u vrtu.",
    speaker: "A.L.",
    age: 3,
    date: "17/05/2024",
    location: "Šibenik",
    year: 2024,
    tags: ["priroda", "životinje"]
  },
  {
    id: "pametnjak",
    letter: "P",
    word: "pametnjak",
    realWord: "naočale",
    definition: "dva prozorčića na nosu kroz koje baka vidi sve sitne mrvice na stolu.",
    speaker: "R.M.",
    age: 5,
    date: "26/02/2024",
    location: "Vukovar",
    year: 2024,
    tags: ["predmeti", "obitelj"]
  },
  {
    id: "prstohvat",
    letter: "P",
    word: "prstohvat",
    realWord: "rukavica",
    definition: "mala zimska vrećica za prste da ne zebu kad radimo snjegovića.",
    speaker: "S.B.",
    age: 4,
    date: "19/12/2023",
    location: "Gospić",
    year: 2023,
    tags: ["zima", "odjeća"]
  }
];

export const CROATIAN_ALPHABET = [
  "A", "B", "C", "Č", "Ć", "D", "Dž", "Đ", "E", "F", "G", "H", "I", 
  "J", "K", "L", "Lj", "M", "N", "Nj", "O", "P", "R", "S", "Š", "T", 
  "U", "V", "Z", "Ž"
];
